name: mink
channels:
  - defaults
dependencies:
  - glob2
  - pandas
  - matplotlib
  - cartopy
  - descartes
  - rasterio
  - ca-certificates
  - certifi
  - openssl
  - rtree
  - seaborn
  - fiona
  - statsmodels
  - netcdf4
  - adjusttext
  - yaml
  - pyyaml
