
settings:

  comparisons_to_run:
    plot_SPAM_vs_FAOSTAT: false
    plot_model_vs_AGMIP: false
    plot_SPAM_country_map: false
    plot_model_country_map: false
    plot_hist_side_by_side: false
    plot_by_country_scatter: false

    # one or both of the following options must be true to get out a comparison statistics csv
    plot_cell_by_cell_scatter: false
    plot_yield_over_time: true


  years:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7

  # whether to process both catastrophe and control, just catastrophe, or just control
  catastrophe_and_or_control:
    - control
    - catastrophe

  faostat_data_location: grassdata/world/FAOSTAT/FAOSTAT_data_en_10-11-2023.csv

crop_codes:

  WHEA:
    crop_nice_name: Wheat
    AGMIP_code: whe
    FAOSTAT_code: Wheat
    snx_description_control: wheat__Aug04_genSNX
    snx_description_catastrophe: wheat__Oct09_catastrophe_genSNX

  MAIZ:
    crop_nice_name: Maize
    AGMIP_code: mai
    FAOSTAT_code: Maize (corn)
    snx_description_control: maize__Sep26_genSNX
    snx_description_catastrophe: maize__Oct08_catastrophe_genSNX
    # snx_description_catastrophe: SKIP_ME

  SOYB:
    crop_nice_name: Soybean
    AGMIP_code: soy
    FAOSTAT_code: Soya beans
    snx_description_control: soybeans__Sep27_genSNX
    snx_description_catastrophe: SKIP_ME

  RICE:
    crop_nice_name: Rice
    AGMIP_code: ric
    FAOSTAT_code: Rice
    snx_description_control: rice__Sep29_genSNX
    snx_description_catastrophe: rice__Oct09_catastrophe_genSNX

  RAPE:
    crop_nice_name: Canola
    AGMIP_code: SKIP_ME
    FAOSTAT_code: Rape or colza seed
    snx_description_control: rapeseed__Sep28_genSNX
    snx_description_catastrophe: rapeseed__Oct10_catastrophe_genSNX

  POTA:
    crop_nice_name: Potatoes
    AGMIP_code: SKIP_ME
    FAOSTAT_code: Potatoes
    # snx_description_control: potatoes__Oct01_genSNX
    snx_description_control: SKIP_ME
    snx_description_catastrophe: SKIP_ME

